#!/bin/bash

echo "🚀 Boostlly Deployment Helper"
echo "================================"
echo ""
echo "📁 Your fresh build is ready at:"
echo "   $(pwd)/apps/web/out"
echo ""
echo "📊 Build details:"
echo "   Size: $(du -sh apps/web/out | cut -f1)"
echo "   Files: $(find apps/web/out -type f | wc -l | tr -d ' ') files"
echo "   Last modified: $(ls -la apps/web/out/ | head -1 | awk '{print $6, $7, $8}')"
echo ""
echo "🌐 Deploy Options:"
echo ""
echo "1. 📤 Manual Netlify Deploy (Recommended):"
echo "   • I've opened: https://app.netlify.com/drop"
echo "   • Drag & drop the 'out' folder from:"
echo "     $(pwd)/apps/web/out"
echo ""
echo "2. 🔗 Alternative - Direct Upload:"
echo "   • Visit: https://app.netlify.com/sites/boostlly/deploys"
echo "   • Click 'Deploy manually'"
echo "   • Upload the 'out' folder"
echo ""
echo "3. 📋 Copy folder path:"
echo "   $(pwd)/apps/web/out"
echo ""
echo "⏱️  Deployment usually takes 1-2 minutes"
echo "✅ Your site will update with all latest features!"
echo ""
echo "🔍 After deployment, check:"
echo "   https://boostlly.netlify.app"
