#!/bin/bash
echo "🧹 FRESH BUILD DEPLOYMENT - ALL CACHES CLEARED!"
echo "==============================================="
echo ""
echo "✅ What was cleared:"
echo "   • All build artifacts (.next, out, dist)"
echo "   • All package builds (core, ui, features, platform)"
echo "   • pnpm store cache (122,332 files removed)"
echo "   • node_modules (fresh install)"
echo "   • Next.js cache"
echo ""
echo "✅ Fresh build completed:"
echo "   • All packages rebuilt from scratch"
echo "   • Deterministic quote selection active"
echo "   • 🌟 General category emoji added"
echo "   • 💪 Motivation category emoji updated"
echo ""
echo "📁 Fresh build location:"
echo "   $(pwd)/apps/web/out"
echo ""
echo "📊 Build details:"
echo "   Size: $(du -sh apps/web/out | awk '{print $1}')"
echo "   Files: $(find apps/web/out -type f | wc -l | tr -d ' ')"
echo "   Build time: $(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" apps/web/out)"
echo ""
echo "🚨 IMPORTANT: Clear Netlify Cache Too!"
echo ""
echo "🌐 Deploy Steps:"
echo ""
echo "1. 📤 Deploy to Netlify:"
echo "   • Open: https://app.netlify.com/drop"
echo "   • Drag & drop: $(pwd)/apps/web/out"
echo ""
echo "2. 🧹 Clear Netlify Cache (CRITICAL!):"
echo "   • Go to: https://app.netlify.com/sites/boostlly/settings/deploys"
echo "   • Click 'Clear cache and retry deploy'"
echo "   • OR go to: https://app.netlify.com/sites/boostlly/deploys"
echo "   • Click the 3 dots on latest deploy → 'Clear cache and retry deploy'"
echo ""
echo "⏱️  Deployment + Cache Clear: 2-3 minutes"
echo ""
echo "✅ After deployment + cache clear:"
echo "   • localhost: 'The only way to do great work is to love what you do.'"
echo "   • deployed: 'The only way to do great work is to love what you do.'"
echo "   • IDENTICAL quotes on both versions!"
echo "   • 🌟 General category with star emoji"
echo "   • 💪 Motivation category with muscle emoji"
echo ""
echo "🔍 Test URLs:"
echo "   • localhost: http://localhost:3000"
echo "   • deployed: https://boostlly.netlify.app"
echo ""
echo "📋 Quick copy path:"
echo "   $(pwd)/apps/web/out"
echo ""
echo "🎯 This will fix the quote mismatch issue!"
